<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d1a96844-5315-442d-831e-bc025a6b9d71</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to  the val1 of Input + the val2 of Input ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
