<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule2</name>
  <uuid>8893858c-41fc-45ec-a62d-92603cf05688</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the val1 of Input is  the val2 of Input
then
	set decision to 2 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
