<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule2-copy2</name>
  <uuid>61c29727-720d-4300-abc6-297b25f1ef78</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the val1 of Input is  the val2 of Input
then
	set decision to 2 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
